services:

  postgres_db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./docker/psql:/var/lib/postgresql
      - ./docker/psql/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres_db

  nginx:
    image: nginx:1.25.4
    ports:
      - '81:80'
    volumes:
      - ./docker/nginx/nginx.conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
